version: '3.4'

services:
  customsclearancecar-api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;
    ports:
      - "5000:5000"
    restart: always

  syncdb-workerservice:
    env_file:
      - .env

  db:
    env_file:
      - .env
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqldata:/var/opt/mssql
        
volumes:
  sqldata:
