version: '3.4'

services:
  proxy:
    ports:
      - "80:80"
    restart: always

  client:
    build: 
      args:
        - api_endpoint=${API_ENDPOINT}
    ports:
      - "9000:80"
    
    restart: always

  api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5005:5000"
    restart: always

  syncdb-workerservice:
    env_file:
      - .env

  db:
    env_file:
      - .env
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqldata:/var/opt/mssql
    restart: always
        
volumes:
  sqldata:
